name: TreasureChest
main: net.ja731j.TreasureChest.TreasureChestMain
authors: ['ja731j']
version: maven-version-number
commands:
  treasurechest:
    description: TreasureChest command
    usage: xP
permissions: